#!/usr/bin/env bash

# Copyright © 2011-2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

args=()
for file in doc/changelog doc/NEWS
do
    if [[ -e $file ]]
    then
        args=(-c "$file")
        break
    fi
done
exec dch "${args[@]}" "$@"

# vim:ts=4 sts=4 sw=4 et
