#!/usr/bin/env bash

# Copyright © 2011-2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

args=()
for path in doc/changelog doc/NEWS
do
    if [[ -e $path ]]
    then
        args=(-c "$path")
        break
    fi
done
if [[ ${#args} -eq 0 ]]
then
    printf '%s: changelog not found\n' "${0##*/}" >&2
    exit 1
fi
exec dch "${args[@]}" "$@"

# vim:ts=4 sts=4 sw=4 et
